import "~/styles/globals.css";

import { Inter } from "next/font/google";
import { cookies } from "next/headers";
console.log(cookies());
import { TRPCReactProvider } from "~/trpc/react";
import Navbar from "../_components/navigation/navbar";
import { Aside } from "../_components/navigation/aside";
import { Footer } from "../_components/navigation/footer";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "T3 Blogging app",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className={`font-sans ${inter.variable}`}>
        <TRPCReactProvider cookies={cookies().toString()}>
          <div>
            <Navbar />
            <Footer />
            {children}
          </div>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
